### ISSUE TITLE
Can I find the server ID in the downloaded demo？

### ISSUE THREAD

**Issue by moge2019** [despa1r1337/ReportBot-v2#2] opened 2019-12-09 11:55 UTC
Can I find the server ID in the downloaded demo？

**Comment by despa1r1337** [comment] 2019-12-09 15:17
> Can I find the server ID in the downloaded demo？

Unfortunately not. You can get it only during the match. Therefore, you need to report cheaters during the match. How to find serverID during a match? [Click me](https://raw.githubusercontent.com/codsec/b1rd_ReportBot_CSGO/master/server%20id.png)

**Comment by moge2019** [comment] 2019-12-09 15:34
> > 我可以在下载的演示中找到服务器ID吗？
> 
> 不幸的是没有。您只能在比赛中获得。因此，您需要在比赛中举报作弊者。如何在比赛中找到serverID？[点击我](https://raw.githubusercontent.com/codsec/b1rd_ReportBot_CSGO/master/server%20id.png)

I just want to report it after the game, but thank you!

**Comment by despa1r1337** [comment] 2019-12-09 15:41
previously, the update could be reported after the match, now unfortunately after the update as it does not happen. If the problem is solved, there are no more questions, you can close this case

**Closed** 2019-12-09 18:37 UTC

**Comment by despa1r1337** [comment] 2019-12-09 19:49
@moge2019  Fixed in d2674e8 , please update and report back.
